# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: Install dependencies with pipenv
      run: |
        pip install pipenv
        pipenv install --deploy --dev
#    - run: pipenv run isort --recursive --diff
#    - run: pipenv run black --check .
    - run: pipenv run flake8
    - run: pipenv run mypy
    - run: pipenv run pytest --cov --cov-fail-under=100
